[package]
name = "janus-plugin-sfu"
description = "Janus SFU for game networking."
version = "0.1.0"
authors = ["Marshall Quander <marshall@quander.me>"]
repository = "https://github.com/mozilla/janus-plugin-sfu"
license = "MPL-2.0"
publish = false

[lib]
crate_type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
atom = "0.3"
janus-plugin = { version = "0.11.1", features = ["refcount"] }
lazy_static = "1.4"
multimap = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rust-ini = "0.13"
jsonwebtoken = "6.0"
